### PR TITLE
Only allow our local ip for the custom ssh port

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
Azure seems to be not happy about exposing a port to the internet hence
we switch to exposing it to only our public ip. Also in the utility
scripts we update the custom port source ip as our current local ip as
our ip might change.

### CODE REVIEW

**Comment by onurctirtir** [comment]
unfortunately local ip would change after a time unless the person that does testing buys static ip service from isp

**Comment by SaitTalhaNisanci** [comment]
>unfortunately local ip would change after a time unless the person that does testing buys static ip service from isp

That is why we add the local (new) ip again when using the scripts such as `./connect-driver` or `.connect.sh`

**Comment by onurctirtir** [comment]
> > unfortunately local ip would change after a time unless the person that does testing buys static ip service from isp
> 
> That is why we add the local (new) ip again when using the scripts such as `./connect-driver` or `.connect.sh`

I didn't realize that, thanks

**Comment by SaitTalhaNisanci** [comment]
For example for finalizing the valgrind, it will already be a different machine. So the ip will be different so we have `./add-local-ip.sh
` which updates the security rule with the current ip, but also the old one is gone. I guess that is okay.

**Review by onurctirtir — APPROVED** [review]

**Pull request merged**
